주문 목록 화면에서 수량 변경, 삭제, 하단 상태 바에 업데이트 완료
movie42/kiosk-frontend pull request #46
Opened 2022-05-15 09:22 UTC by sycho09

# 개요
고객 주문 목록 화면에서 수량 변경 및 삭제, 하단 상태 바에 총 수량 및 가격 반영

# 작업 내용
고객 주문 목록 화면에서 수량 변경 및 삭제, 하단 상태 바에 총 수량 및 가격 반영되도록 업데이트 했습니다. 
옵션 포함한 주문 목록 생성, 주문 목록에서 옵션 값이 다를 경우 분리해서 보여줍니다.
결제 이후 메인으로 돌아가는 기능 구현은 아웃라인만 완료했고 화면 구현 및 세부적인 내용 업데이트 필요합니다. 
(추가로 결제진행 모달 창에서 전체 주문 메뉴 불러오는 기능 필요합니다)

# 스크린샷 
필요하다면 첨부해주세요.

2022-05-15 09:26 UTC, tjsry0466 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
else는 안써도 되지 않을까요?

2022-05-15 09:27 UTC, tjsry0466 commented on src/Page/Client/Modal/MenuItemModalChildren.tsx
> +      (selectedItem[0].option?.length !== 0 && selectedOption === "")
해당 조건이 어떤 조건을 의미하는건지 알기 힘든데 변수로 정의해서 사용해주세요

2022-05-15 09:28 UTC, tjsry0466 commented on src/Page/Client/Modal/MenuItemModalChildren.tsx
> +      } else {
depth를 최대한 줄이는 방법으로 작성해주세요

2022-05-15 09:29 UTC, tjsry0466 commented on src/Page/Client/Modal/MenuItemModalChildren.tsx
> +              return a.productId - b.productId;
마찬가지입니다 else는 되도록이면 사용하지 않아도 되게 작성해주세요

2022-05-15 09:30 UTC, tjsry0466 commented on src/Page/Client/Modal/PaymentModalChildren.tsx
> +      )}
삼한연산자는 2번이상 중첩해서 작성하지 말아주세요

2022-05-15 09:35 UTC, tjsry0466 commented
@sycho09 작업한 내용에 대해 화면에 보여지는 부분은 PR에 스크린샷 첨부 부탁드립니다

2022-05-15 10:56 UTC, movie42 requested changes
if문 else 중첩을 수정하는것이 좋을 것 같습니다.

2022-05-15 10:56 UTC, movie42 commented on src/Page/Client/ClientMenu.tsx
>  export interface IOrderSelectedItem {
혹시 IOrderSelectedItem interface가 컴포넌트의 props와 연관이 없고
order select의 상태와 관련이 있는 atom이 있다면 그곳으로 옮기는것도 좋을 것 같습니다.

2022-05-15 10:56 UTC, movie42 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
제 생각에도 정렬에 대한 return 을 1 또는 -1로 하고 있는데 어느 부분이 예외사항인지 잘 모르겠습니다. 설명 해주실 수 있으신가요?

2022-05-15 10:56 UTC, movie42 commented on src/Page/Client/Modal/MenuItemModalChildren.tsx
> +      (selectedItem[0].option?.length !== 0 && selectedOption === "")
넘겨진 selectedItem을 구조 분해 할당을 해서 정의하는건 어떨까요?

2022-05-15 10:56 UTC, movie42 commented on src/Page/Client/Modal/MenuItemModalChildren.tsx
> +              return a.productId - b.productId;
if의 조건을 
if(true)를 사용하는 것보다 
if(!false)를 사용해보는 건 어떨까요? 
그럼 else를 줄이고 depth를 줄일 수 있을 것 같아요.

2022-05-15 10:57 UTC, movie42 reviewed
if와 삼항 연산자 중첩을 최소화하는 것이 좋을 것같습니다.

2022-05-16 11:37 UTC, tjsry0466 commented
@sycho09 리뷰확인 부탁드립니다

2022-05-17 02:24 UTC, minsoo0715 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
if문 내에서 a.option && b.option을 만족 시킬때 a.option-b.option을 반환하셔도 될 것 같습니다.

2022-05-17 02:30 UTC, minsoo0715 commented on src/Page/Client/ClientSelectList.tsx
> +      ].sort((a, b) => (a.productId > b.productId ? 1 : -1))
a.productId - b.productId를 단순 반환해도 결과는 같습니다.

2022-05-17 02:36 UTC, minsoo0715 commented on src/Page/Client/Modal/MenuItemModalChildren.tsx
> +          ].sort(function (a, b) {
> if문 내에서 a.option && b.option을 만족 시킬때 a.option-b.option을 반환하셔도 될 것 같습니다.

마찬가지입니다.

2022-05-17 08:05 UTC, sycho09 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
else 대신 if문 밖에서 return a.productId - b.productId; 해주면 될까요? 상품이 다를 경우 비교하는 함수가 있어야 될 거 같습니다.

2022-05-17 08:08 UTC, minsoo0715 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
네 맞습니다

2022-05-17 08:08 UTC, sycho09 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
option 값이 string이라서 바로 연산이 안되는거 같습니다.
if (a.productId === b.productId) {
          return a?.option > b?.option ? 1 : -1;
} 
조건을 제거해도 삼항연산자를 사용해야 하는데 다른 방법이 있을까요?

2022-05-17 08:10 UTC, minsoo0715 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
그냥 a.option - b.option 반환하셔도 됩니다

2022-05-17 08:11 UTC, minsoo0715 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
아 string이군요..

2022-05-17 08:23 UTC, minsoo0715 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
그럼 early return 부분만 수정해주시면 될 것 같습니다. 제가 헷갈렸네요

2022-05-17 13:21 UTC, tjsry0466 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
근데 정렬을 꼭 해야하나요?

2022-05-18 03:53 UTC, movie42 commented on src/Page/Client/ClientSelectList.tsx
> +        } else {
@tjsry0466  정렬을 하지 않으면 아이템 순서가 뒤바뀝니다.

2022-05-23 04:47 UTC, movie42 approved these changes
수정한 코드 잘 봤습니다.
일단 sort 부분은 제가 생각했을 때 다른 해결 방법을 찾아야할 것 같습니다. 저도 sort를 하고 있는데 생각보다 불편한 것 같습니다. 그리고 selected라는 key 값을 만들게 되면 서버에게 보낼때 그 값도 처리를 해야하는데 지금 코드는 정답이 아닌 것 같네요.
코드 상으로는 품질상 merge를 해도 될 것 같습니다. merge 해주세요!

2022-05-24 05:35 UTC, merged