Feature/landing signup
movie42/kiosk-frontend pull request #71
Opened 2022-06-23 18:51 UTC by sycho09

# 개요
회원가입, 회원가입/가게 동시 등록

# 작업 내용
1. 회원 정보만 등록, 회원 정보와 가게 등록을 동시에 할 경우 각각 회원 가입 기능 구현

# 스크린샷 
필요하다면 첨부해주세요.

pull requests 내용을 작성하실때 'resolve: #[이슈넘버]'를 넣어주시면 merge될 때, 깃허브에서 자동으로 이슈를 close해줍니다.

2022-06-24 09:01 UTC, movie42 requested changes
몇몇 부분만 수정하고 추가 PR 날려주시면 될 것 같습니다.

2022-06-24 09:01 UTC, movie42 commented on src/Page/Landing/SignUp.tsx
> +      localStorage.setItem("refreshToken", refreshToken);
user 정보를 localstorage 저장하는 방법이 변경되어서 어떤식으로 저장할 것인지 협의 후에 변경이 필요합니다.

2022-06-24 09:01 UTC, movie42 commented on src/Page/Landing/SignUp.tsx
> +      handleErrorMessage(error, setErrorState);
현재 handleErrorMessage가 동작을 하지 않는데 서버에서 넘어오는 에러 객체의 형태가 조금 달라서 대응하기가 어렵습니다. 이 부분을 이 함수로 처리할 것인지 아니면 다른 방법이 필요한지 생각 해봐야할것같습니다.

2022-06-24 09:01 UTC, movie42 commented on src/Page/Landing/SignUp.tsx
> +        isLogin: true,
이 단계에서 로그인이 true가 되면 프라이벳 라우터에서 isLogin을 전역으로 감지하고 있기 때문에 회원가입이 도중에 중단되는 이슈가 있었습니다. meQuery를 불러올 때 isLogin을 true로 하는 것이 좋을 것 같습니다.

2022-06-24 09:01 UTC, movie42 commented on src/Page/Landing/SignUp.tsx
> +      refetch();
refetch는 어떤 이유에서 넣은 건지 공유해주세요. 설명을 듣고 저도 사용할 수 있으면 적용해보려고 합니다.

2022-06-24 09:01 UTC, movie42 commented on src/Page/Landing/SignUp.tsx
> +        navigate("/login");
혹시 이곳에서 login으로 리다이렉트 됐을 때, 어떻게 동작하나요? 자동 로그인에 성공하던가요?

2022-06-24 09:01 UTC, movie42 commented on src/Page/Landing/SignUp.tsx
> +  const [saveStore, setSaveStore] = useState(false);
hook은 코드 최상단에 함께 모아놓는게 좋을 것같습니다.

2022-06-24 09:01 UTC, movie42 commented on src/Page/Landing/SignUp.tsx
> +  }, [saveStore, setSaveStore]);
useEffect안에서 사용되고 있지 않기 때문에 setSaveStore는 의존성 배열에 포함되지 않아도 될것같은데요?

2022-06-24 09:01 UTC, movie42 commented on src/Page/Landing/SignUp.tsx
> +  const onSubmit = async (data: ISignUpProps) => {
async를 사용한 이유가 무엇일까요?

2022-06-25 10:43 UTC, sycho09 commented on src/Page/Landing/SignUp.tsx
> +      localStorage.setItem("refreshToken", refreshToken);
변경된 방법으로 업데이트 하겠습니다.

2022-06-25 10:48 UTC, sycho09 commented on src/Page/Landing/SignUp.tsx
> +      refetch();
이 시점에서 refetch 를 실행하면 받은 토큰으로 추후 meQuery 의 user 정보를 불러오고 그 정보로 로그인이 가능해서 사용했습니다.

2022-06-25 10:50 UTC, sycho09 commented on src/Page/Landing/SignUp.tsx
> +        navigate("/login");
로그인 정보가 다 들어오고 로그인이 성공하는 것은 확인했습니다. 로그인 이후 다른 기능들은 테스트 해보지 않아서 추가 다른 에러는 없는지 확인이 필요합니다.

2022-06-25 10:50 UTC, sycho09 commented on src/Page/Landing/SignUp.tsx
> +  const [saveStore, setSaveStore] = useState(false);
반영하겠습니다.

2022-06-28 12:58 UTC, movie42 approved these changes

2022-06-28 14:19 UTC, merged